# Generated by Django 6.0.1 on 2026-04-26 02:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_rename_order_question_stt_test_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
