# Generated by Django 6.0.1 on 2026-04-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='title',
            field=models.CharField(default='a'),
        ),
    ]
