# Generated by Django 6.0.1 on 2026-04-10 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_list_article_article_list_series_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_list',
        ),
        migrations.AddField(
            model_name='article_list',
            name='articles',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.article'),
            preserve_default=False,
        ),
    ]
