# Generated by Django 6.0.1 on 2026-04-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_article_article_list_article_list_articles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article_list',
            old_name='articles',
            new_name='article',
        ),
    ]
