# Generated by Django 6.0.1 on 2026-04-10 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_articles_article_list_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_list',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article'),
        ),
        migrations.AlterField(
            model_name='article_list',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.series'),
        ),
    ]
