# Generated by Django 6.0.1 on 2026-05-19 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodeRun',
            new_name='Practice',
        ),
    ]
