# Generated by Django 6.0.1 on 2026-05-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_remove_practice_error_remove_practice_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practice',
            name='title',
            field=models.CharField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='stt',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
