# Generated by Django 6.0.1 on 2026-05-20 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_practice_content_practice_title_testcase_stt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpractice',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.practice'),
        ),
        migrations.AlterUniqueTogether(
            name='userpractice',
            unique_together={('user', 'practice')},
        ),
        migrations.DeleteModel(
            name='UserTestCase',
        ),
    ]
