# Generated by Django 6.0.1 on 2026-05-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_alter_userpractice_practice_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpractice',
            unique_together=set(),
        ),
    ]
